import { LabelT } from './label.type'

export enum LabelActionTypes {
  LIST_ALL_REQUEST = 'LABEL/LIST_ALL_REQUEST',
  LIST_ALL_SUCCESS = 'LABEL/LIST_ALL_SUCCESS',
  LIST_ALL_FAILURE = 'LABEL/LIST_ALL_FAILURE',
  CREATE_REQUEST = 'LABEL/CREATE_REQUEST',
  CREATE_SUCCESS = 'LABEL/CREATE_SUCCESS',
  CREATE_FAILURE = 'LABEL/CREATE_FAILURE',
  EDIT_REQUEST = 'LABEL/EDIT_REQUEST',
  EDIT_SUCCESS = 'LABEL/EDIT_SUCCESS',
  EDIT_FAILURE = 'LABEL/EDIT_FAILURE',
  DELETE_REQUEST = 'LABEL/DELETE_REQUEST',
  DELETE_SUCCESS = 'LABEL/DELETE_SUCCESS',
  DELETE_FAILURE = 'LABEL/DELETE_FAILURE',
}

export type LabelState = {
  isLoading: boolean
  items: LabelT[]
}
