import { TelevisionT } from './television.type'

export enum TelevisionActionTypes {
  LIST_ALL_REQUEST = 'TELEVISION/LIST_ALL_REQUEST',
  LIST_ALL_SUCCESS = 'TELEVISION/LIST_ALL_SUCCESS',
  LIST_ALL_FAILURE = 'TELEVISION/LIST_ALL_FAILURE',
  LIST_ALL_JOIN_REQUEST = 'TELEVISION/LIST_ALL_JOIN_REQUEST',
  LIST_ALL_JOIN_SUCCESS = 'TELEVISION/LIST_ALL_JOIN_SUCCESS',
  LIST_ALL_JOIN_FAILURE = 'TELEVISION/LIST_ALL_JOIN_FAILURE',
  CREATE_REQUEST = 'TELEVISION/CREATE_REQUEST',
  CREATE_SUCCESS = 'TELEVISION/CREATE_SUCCESS',
  CREATE_FAILURE = 'TELEVISION/CREATE_FAILURE',
  EDIT_REQUEST = 'TELEVISION/EDIT_REQUEST',
  EDIT_SUCCESS = 'TELEVISION/EDIT_SUCCESS',
  EDIT_FAILURE = 'TELEVISION/EDIT_FAILURE',
  DELETE_REQUEST = 'TELEVISION/DELETE_REQUEST',
  DELETE_SUCCESS = 'TELEVISION/DELETE_SUCCESS',
  DELETE_FAILURE = 'TELEVISION/DELETE_FAILURE',
}

export type TelevisionState = {
  isLoading: boolean
  items: TelevisionT[]
}
