import { ContentT } from './content.type'

export enum ContentActionTypes {
  LIST_ALL_REQUEST = 'CONTENT/LIST_ALL_REQUEST',
  LIST_ALL_SUCCESS = 'CONTENT/LIST_ALL_SUCCESS',
  LIST_ALL_FAILURE = 'CONTENT/LIST_ALL_FAILURE',
  CREATE_REQUEST = 'CONTENT/CREATE_REQUEST',
  CREATE_SUCCESS = 'CONTENT/CREATE_SUCCESS',
  CREATE_FAILURE = 'CONTENT/CREATE_FAILURE',
  EDIT_REQUEST = 'CONTENT/EDIT_REQUEST',
  EDIT_SUCCESS = 'CONTENT/EDIT_SUCCESS',
  EDIT_FAILURE = 'CONTENT/EDIT_FAILURE',
  DELETE_REQUEST = 'CONTENT/DELETE_REQUEST',
  DELETE_SUCCESS = 'CONTENT/DELETE_SUCCESS',
  DELETE_FAILURE = 'CONTENT/DELETE_FAILURE',
}

export type ContentState = {
  isLoading: boolean
  items: ContentT[]
}
