# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#=======================================================
# General Configuration
#=======================================================
    config.vm.box = "ubuntu/focal64"
    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |v|

      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--ioapic", "on"]

    end
    config.vm.box_check_update = false

#=======================================================
# Master
#=======================================================
    config.vm.define "master" do |node|
      node.vm.network "private_network", ip: "192.168.56.11"
                node.vm.hostname = "master"


                config.vm.provision "file", source: "./ssh-key.pub", destination: "~/.ssh/ssh-key.pub"
                config.vm.provision "shell", inline: <<-SHELL
                        cat /home/vagrant/.ssh/ssh-key.pub >> /home/vagrant/.ssh/authorized_keys
                SHELL

      config.vm.provider "virtualbox" do |v|
      # Creating a virtual disk called "diskn2" with a size of 100GB
        v.customize ["createhd", "--filename", "./diskn1", "--size", 100 * 1024]
      # Attaching the newly created virtual disk to our node
        v.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", 3, "--device", 0, "--type", "hdd", "--medium", "./diskn1"]
      end
    end
#=======================================================
# Worker 1
#=======================================================
    config.vm.define "worker1" do |node|
      node.vm.network "private_network", ip: "192.168.56.101"
                node.vm.hostname = "worker1"

                config.vm.provision "file", source: "./ssh-key.pub", destination: "~/.ssh/ssh-key.pub"
                config.vm.provision "shell", inline: <<-SHELL
                        cat /home/vagrant/.ssh/ssh-key.pub >> /home/vagrant/.ssh/authorized_keys
                SHELL
      config.vm.provider "virtualbox" do |v|
      # Creating a virtual disk called "diskn2" with a size of 100GB
        v.customize ["createhd", "--filename", "./diskn2", "--size", 100 * 1024]
      # Attaching the newly created virtual disk to our node
        v.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", 3, "--device", 0, "--type", "hdd", "--medium", "./diskn2"]
      end
    end
#=======================================================
# Worker 2
#=======================================================
    config.vm.define "worker2" do |node|
      node.vm.network "private_network", ip: "192.168.56.102"
                node.vm.hostname = "worker2"

                config.vm.provision "file", source: "./ssh-key.pub", destination: "~/.ssh/ssh-key.pub"
                config.vm.provision "shell", inline: <<-SHELL
                        cat /home/vagrant/.ssh/ssh-key.pub >> /home/vagrant/.ssh/authorized_keys
                SHELL
      config.vm.provider "virtualbox" do |v|
      # Creating a virtual disk called "diskn2" with a size of 100GB
        v.customize ["createhd", "--filename", "./diskn3", "--size", 100 * 1024]
      # Attaching the newly created virtual disk to our node
        v.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", 3, "--device", 0, "--type", "hdd", "--medium", "./diskn3"]
      end
    end
#=======================================================
# Worker 3
#=======================================================
    config.vm.define "worker3" do |node|
      node.vm.network "private_network", ip: "192.168.56.103"
                node.vm.hostname = "worker3"

                config.vm.provision "file", source: "./ssh-key.pub", destination: "~/.ssh/ssh-key.pub"
                config.vm.provision "shell", inline: <<-SHELL
                        cat /home/vagrant/.ssh/ssh-key.pub >> /home/vagrant/.ssh/authorized_keys
                SHELL
      config.vm.provider "virtualbox" do |v|
      # Creating a virtual disk called "diskn2" with a size of 100GB
        v.customize ["createhd", "--filename", "./diskn4", "--size", 100 * 1024]
      # Attaching the newly created virtual disk to our node
        v.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", 3, "--device", 0, "--type", "hdd", "--medium", "./diskn4"]
      end
    end
end
