FROM node:18-alpine as build-stage

# RUN apk add g++ make py3-pip

WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn
COPY . .
RUN yarn build

FROM nginx:latest
COPY --from=build-stage /app/dist/ /usr/share/nginx/html
