FROM node:18-alpine

RUN apk add g++ make py3-pip

# Create app directory
RUN mkdir -p /dashboard

WORKDIR /dashboard

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY . .

ENV PORT=3000
EXPOSE 3000
CMD ["yarn", "start:dev"]
