FROM node:18-alpine

RUN apk add g++ make py3-pip

RUN yarn global add pnpm

WORKDIR /services

COPY package.json .
COPY yarn.lock .
COPY pnpm-* .
COPY dashboard/package.json ./dashboard/
COPY packages/validation/package.json ./packages/validation/

RUN pnpm install --filter "./packages/**" --filter dashboard

COPY . .

ENV PORT=3000
EXPOSE 3000

CMD [ "yarn", "start:dashboard:dev" ]
