CREATE TABLE IF NOT EXISTS `monitor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `allProcessesAreRunning`: BOOLEAN,
  `appIsVisible`: BOOLEAN,
  `availableMem`: FLOAT,
  `availableStorage`: FLOAT,
  `availableStorageUnit`: VARCHAR(5),
  `currentDate`: DATETIME,
  `currentVersionApp`: VARCHAR(5),
  `currentlyPlayingContentId`: INT,
  `externalStoragePermissionGranted`: BOOLEAN,
  `isAnyAlertPlaying`: BOOLEAN,
  `isAnyContentPlaying`: BOOLEAN,
  `isExternalStorageConnected`: BOOLEAN,
  `memUnit`: VARCHAR(5),
  `sdkVersion`: INT,
  `totalMem`: FLOAT,
  `totalStorage`: FLOAT,
  `totalStorageUnit`: VARCHAR(5),
  `tvCode`: VARCHAR(6),
  `useExternalStorage`: BOOLEAN,
  PRIMARY KEY (`id`));