FROM node:18-alpine

RUN yarn global add pnpm

WORKDIR /services

COPY package.json .
COPY yarn.lock .
COPY pnpm-* .
COPY api/package.json ./api/
COPY packages/validation/package.json ./packages/validation/
COPY packages/lib/package.json ./packages/lib/

RUN pnpm install --filter "./packages/**" --filter api

COPY . .

CMD [ "yarn", "start:api:dev" ]
