export const DRAWER_MENU_LABEL = {
  DASHBOARD: 'DASHBOARD',
  USERS: 'USERS',
  INSTITUTIONS: 'INSTITUTIONS',
  CONTENTS: 'CONTENTS',
  TELEVISIONS: 'TELEVISIONS',
  LABELS: 'LABELS',
  PRODUCT_LIST: 'PRODUCT_LIST',
};
