export const PATH_NAME = {
  ROOT: '/',
  ERROR_404: '/404',
  ERROR_403: '/403',
  DASHBOARD: '/dashboard',
  PLAY_BACKGROUND: '/playbackground',
  LOGIN: '/login',
  INSTITUTION: '/institutions',
  CONTENT: '/contents',
  TELEVISION: '/televisions',
  LABEL: '/labels',
  AGENDA: '/agendas',
  USERS: '/users',
  KANBAN: '/kanban',
};
