import { AlertT } from './alert.type'

export enum AlertActionTypes {
  LIST_ALL_REQUEST = 'ALERT/LIST_ALL_REQUEST',
  LIST_ALL_SUCCESS = 'ALERT/LIST_ALL_SUCCESS',
  LIST_ALL_FAILURE = 'ALERT/LIST_ALL_FAILURE',
  CREATE_REQUEST = 'ALERT/CREATE_REQUEST',
  CREATE_SUCCESS = 'ALERT/CREATE_SUCCESS',
  CREATE_FAILURE = 'ALERT/CREATE_FAILURE',
  EDIT_REQUEST = 'ALERT/EDIT_REQUEST',
  EDIT_SUCCESS = 'ALERT/EDIT_SUCCESS',
  EDIT_FAILURE = 'ALERT/EDIT_FAILURE',
  DELETE_REQUEST = 'ALERT/DELETE_REQUEST',
  DELETE_SUCCESS = 'ALERT/DELETE_SUCCESS',
  DELETE_FAILURE = 'ALERT/DELETE_FAILURE',
}

export type AlertsState = {
  isLoading: boolean
  items: AlertT[]
}
