import { AgendaT } from './agenda.type'

export enum AgendaActionTypes {
  LIST_ALL_REQUEST = 'AGENDA/LIST_ALL_REQUEST',
  LIST_ALL_SUCCESS = 'AGENDA/LIST_ALL_SUCCESS',
  LIST_ALL_FAILURE = 'AGENDA/LIST_ALL_FAILURE',
  CREATE_REQUEST = 'AGENDA/CREATE_REQUEST',
  CREATE_SUCCESS = 'AGENDA/CREATE_SUCCESS',
  CREATE_FAILURE = 'AGENDA/CREATE_FAILURE',
  EDIT_REQUEST = 'AGENDA/EDIT_REQUEST',
  EDIT_SUCCESS = 'AGENDA/EDIT_SUCCESS',
  EDIT_FAILURE = 'AGENDA/EDIT_FAILURE',
  DELETE_REQUEST = 'AGENDA/DELETE_REQUEST',
  DELETE_SUCCESS = 'AGENDA/DELETE_SUCCESS',
  DELETE_FAILURE = 'AGENDA/DELETE_FAILURE',
}

export type AgendasState = {
  isLoading: boolean
  items: AgendaT[]
}
