name: deploy_docker_images

on:
  push:
    branches: ['main']

jobs:
  backend_integration_tests:
    name: Backend integration tests
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create .env
      run: cp .env.example .env

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/distritv-api:latest,${{ secrets.DOCKERHUB_USERNAME }}/distritv-api:${{ github.sha }}
        file: Dockerfile.development
      working-directory: services/api

    - name: Start containers
      run: docker-compose up -d -f "docker-compose.prod.yml"

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: Install dependencies
      run: yarn
      working-directory: services/api

    - name: Check API status
      run: docker-compose logs api

    - name: Run tests
      run: yarn test
      working-directory: services/api

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.prod.yml" down

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/distritv-api:latest,${{ secrets.DOCKERHUB_USERNAME }}/distritv-api:${{ github.sha }}
        file: Dockerfile.development
      working-directory: services/api
