name: deploy_docker_images

on:
  push:
    branches: ['main']

jobs:
  backend_integration_tests:
    name: Backend integration tests
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create .env
      run: cp .env.example .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build backend
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}-api:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}-api:${{ github.sha }}
        file: Dockerfile.production
        context: "{{defaultContext}}:services/api"
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build frontend
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}-dashboard:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}-dashboard:${{ github.sha }}
        file: Dockerfile.production
        context: "{{defaultContext}}:services/api"
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Start backend services
      run: docker-compose -f "docker-compose.test.yml" up -d db cache api

    - name: Start frontend and proxy
      run: docker-compose -f "docker-compose.test.yml" up -d

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: Install dependencies
      run: yarn
      working-directory: services/api

    - name: Check API status
      run: docker-compose logs api

    - name: Run tests
      run: yarn test
      working-directory: services/api

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.test.yml" down -v

    - name: Push backend
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}-api:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}-api:${{ github.sha }}
        file: Dockerfile.production
        context: "{{defaultContext}}:services/api"
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Push frontend
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}-dashboard:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}-dashboard:${{ github.sha }}
        file: Dockerfile.production
        context: "{{defaultContext}}:services/api"
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        username: ${{ secrets.SERVER_SSH_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          cd ${{ env.SERVER_PROJECT_DIR }} && docker compose -f docker-compose.prod.yml up -d --build --force-recreate
